version: 2
jobs:
   build:
     environment:
       - GIT_LFS_SKIP_SMUDGE: 1
     docker:
       #- image: macjustice/git-lfs
       - image: ubuntu:xenial
     steps:
       - lfs/install
       - lfs/checkout
