version: 2
workflows:
  version: 2
  deploy-site:
    jobs:
    - whatever

jobs:
  whatever:
    docker:
    - image: ubuntu

    steps:
      - checkout
      - run:
          name: Install Git LFS
          command: |
            apt-get update
            apt-get install -y curl git-lfs openssh-client
            curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
            git lfs install
            mkdir -p ~/.ssh
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
