version: 2
jobs:
  build:
    environment:
    - GIT_LFS_SKIP_SMUDGE: 1
    docker:
    - image: macjustice/git-lfs
    steps:
    - run:
        name: install LFS
        command: "apt-get update && apt-get -y install wget git -y \nwget https://packagecloud.io/github/git-lfs/packages/ubuntu/xenial/git-lfs_2.1.1_amd64.deb/download\
          \ -O git-lfs_2.1.1_amd64.deb\ndpkg -i git-lfs_2.1.1_amd64.deb\n"
    - run:
        name: Git LFS (install Git Large File Storage)
        command: |
          mkdir -p ~/.ssh
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          ssh git@github.com git-lfs-authenticate "${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}" download
