parameters:
  rspec_glob:
    type: string
    default: "spec/**/*_spec.rb"
steps:
  - run:
      name: Run rspec in parallel
      command: |
        # Determine test subset to run on each container and print diagnostics
        TEST_FILES=$(circleci tests glob << parameters.rspec_glob >> | \
                        circleci tests split)
        echo "running " $(echo $TEST_FILES | wc -w) " tests files on this container:"
        echo "$TEST_FILES"

        bundle exec rspec --profile 10 \
                          --format RspecJunitFormatter \
                          --out CIRCLE_TEST_REPORTS/rspec.xml \
                          --format documentation \
                          $TEST_FILES

  - store_test_results:
      path: $CIRCLE_TEST_REPORTS

  - store_artifacts:
      path: $CIRCLE_ARTIFACTS
